### ISSUE TITLE
Incompatible with latest pylint

### ISSUE THREAD

**Issue by frewsxcv** [educreations/ec-pylint-checkers#1]
```
AssertionError: Message symbol None is already defined
```

This error appears when this plugin is enabled and I run `pylint`

**Comment by meastman** [comment]
Anyone object to deleting this repo since it's broken and we don't use it?

**Comment by frewsxcv** [comment]
I was originally thinking we could just put a message on the README indicating it's no longer maintained. I don't feel strongly about either

**Comment by meastman** [comment]
> I was originally thinking we could just put a message on the README indicating it's no longer maintained.

Added in e5df68b

**Comment by frewsxcv** [comment]
`WONTFIX`
